=== viralbhoi/BVM/2CP08/lab-8/emp.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="employee_info">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="employee" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Name" type="xs:string"></xs:element>
                            <xs:element name="Department" type="xs:string"></xs:element>
                            <xs:element name="telephone" type="xs:string"></xs:element>
                            <xs:element name="email" type="xs:string"></xs:element>
                        </xs:sequence>
                        <xs:attribute name="employee_number" type="xs:int"></xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== viralbhoi/BVM/2CP08/lab-8/1.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="style.xsl"?>

<employee_info xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
               xsi:noNamespaceSchemaLocation="emp.xsd">
    
    <employee employee_number="1">
        <Name>Amit</Name>
        <Department>CP</Department>
        <telephone>9879879879</telephone>
        <email>abc@gmail.com</email>
    </employee>

    <employee employee_number="2">
        <Name>Rahul</Name>
        <Department>IT</Department>
        <telephone>9876543210</telephone>
        <email>rahul@example.com</email>
    </employee>

</employee_info>
